from click.testing import CliRunner

from argus.cli import main

FULL_CONFIG = """\
packs:
  - tdd
  - atomic-commit
platforms:
  - claude
  - opencode
  - copilot
  - cursor
"""

GEMINI_CONFIG = """\
packs:
  - tdd
platforms:
  - gemini
"""


def test_generate_produces_claude_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert (tmp_path / "CLAUDE.md").exists()
    assert (tmp_path / ".claude/rules/tdd.md").exists()
    assert (tmp_path / ".claude/rules/atomic-commit.md").exists()
    assert (tmp_path / ".claude/skills/tdd/SKILL.md").exists()


def test_generate_produces_opencode_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert (tmp_path / "opencode.json").exists()
    assert (tmp_path / ".opencode/skills/tdd/SKILL.md").exists()
    assert (tmp_path / ".opencode/commands/tdd.md").exists()


def test_generate_produces_copilot_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert (tmp_path / ".github/copilot-instructions.md").exists()


def test_generate_produces_cursor_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert (tmp_path / ".cursor/rules/tdd.md").exists()
    assert (tmp_path / ".cursor/rules/atomic-commit.md").exists()


def test_agents_md_written_once_with_multiple_platforms(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0
    # AGENTS.md mentioned in output — confirm only once written, not duplicate error
    assert result.output.count("AGENTS.md") == 1


def test_generated_files_have_header(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    claude_md = (tmp_path / "CLAUDE.md").read_text()
    assert "Generated by argus" in claude_md


def test_claude_md_points_to_rules_directory(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    content = (tmp_path / "CLAUDE.md").read_text()
    assert ".claude/rules/" in content
    assert "Never write or modify production code" not in content


def test_check_mode_exits_nonzero_on_stale_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    (tmp_path / "CLAUDE.md").write_text("# manually edited")
    result = runner.invoke(main, ["generate", "--check", "--project-root", str(tmp_path)])
    assert result.exit_code == 1


def test_check_mode_exits_zero_when_files_current(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    result = runner.invoke(main, ["generate", "--check", "--project-root", str(tmp_path)])
    assert result.exit_code == 0


def test_generate_produces_gemini_files(tmp_path):
    """Given a config with gemini platform, generate writes GEMINI.md with pack content."""
    (tmp_path / ".argus.yml").write_text(GEMINI_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert (tmp_path / "GEMINI.md").exists()
    assert "TDD" in (tmp_path / "GEMINI.md").read_text()


TYPE_SAFETY_CONFIG = """\
packs:
  - type-safety
platforms:
  - claude
"""


def test_type_safety_pack_appears_in_packs_list():
    """Given packs list is invoked, type-safety appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "type-safety" in result.output


def test_type_safety_pack_show_renders_content():
    """Given packs show type-safety is invoked, mypy appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "type-safety"])
    assert result.exit_code == 0
    assert "mypy" in result.output


def test_type_safety_pack_generate_injects_content(tmp_path):
    """Given a type-safety+claude config, generate writes mypy content to .claude/rules/type-safety.md."""
    (tmp_path / ".argus.yml").write_text(TYPE_SAFETY_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "mypy" in (tmp_path / ".claude/rules/type-safety.md").read_text()


ERROR_HANDLING_CONFIG = """\
packs:
  - error-handling
platforms:
  - claude
"""


def test_error_handling_pack_appears_in_packs_list():
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "error-handling" in result.output


def test_error_handling_pack_show_renders_content():
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "error-handling"])
    assert result.exit_code == 0
    assert "system boundaries" in result.output


def test_error_handling_pack_generate_injects_content(tmp_path):
    (tmp_path / ".argus.yml").write_text(ERROR_HANDLING_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "system boundaries" in (tmp_path / ".claude/rules/error-handling.md").read_text()
