from click.testing import CliRunner

from argus.cli import main

FULL_CONFIG = """\
packs:
  - tdd
  - atomic-commit
platforms:
  - claude
  - opencode
  - copilot
  - cursor
"""

GEMINI_CONFIG = """\
packs:
  - tdd
platforms:
  - gemini
"""


def test_generate_produces_claude_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert (tmp_path / "CLAUDE.md").exists()
    assert (tmp_path / ".claude/rules/tdd.md").exists()
    assert (tmp_path / ".claude/rules/atomic-commit.md").exists()
    assert (tmp_path / ".claude/skills/tdd/SKILL.md").exists()


def test_generate_produces_opencode_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert (tmp_path / "opencode.json").exists()
    assert (tmp_path / ".opencode/skills/tdd/SKILL.md").exists()
    assert (tmp_path / ".opencode/commands/tdd.md").exists()


def test_generate_produces_copilot_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert (tmp_path / ".github/copilot-instructions.md").exists()


def test_generate_produces_cursor_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert (tmp_path / ".cursor/rules/tdd.md").exists()
    assert (tmp_path / ".cursor/rules/atomic-commit.md").exists()


def test_agents_md_written_once_with_multiple_platforms(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0
    # AGENTS.md mentioned in output — confirm only once written, not duplicate error
    assert result.output.count("AGENTS.md") == 1


def test_generated_files_have_header(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    claude_md = (tmp_path / "CLAUDE.md").read_text()
    assert "Generated by argus" in claude_md


def test_claude_md_points_to_rules_directory(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    content = (tmp_path / "CLAUDE.md").read_text()
    assert ".claude/rules/" in content
    assert "Never write or modify production code" not in content


def test_check_mode_exits_nonzero_on_stale_files(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    (tmp_path / "CLAUDE.md").write_text("# manually edited")
    result = runner.invoke(main, ["generate", "--check", "--project-root", str(tmp_path)])
    assert result.exit_code == 1


def test_check_mode_exits_zero_when_files_current(tmp_path):
    (tmp_path / ".argus.yml").write_text(FULL_CONFIG)
    runner = CliRunner()
    runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    result = runner.invoke(main, ["generate", "--check", "--project-root", str(tmp_path)])
    assert result.exit_code == 0


def test_generate_produces_gemini_files(tmp_path):
    """Given a config with gemini platform, generate writes GEMINI.md with pack content."""
    (tmp_path / ".argus.yml").write_text(GEMINI_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert (tmp_path / "GEMINI.md").exists()
    assert "TDD" in (tmp_path / "GEMINI.md").read_text()


TYPE_SAFETY_CONFIG = """\
packs:
  - type-safety
platforms:
  - claude
"""


def test_type_safety_pack_appears_in_packs_list():
    """Given packs list is invoked, type-safety appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "type-safety" in result.output


def test_type_safety_pack_show_renders_content():
    """Given packs show type-safety is invoked, mypy appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "type-safety"])
    assert result.exit_code == 0
    assert "mypy" in result.output


def test_type_safety_pack_generate_injects_content(tmp_path):
    """Given a type-safety+claude config, generate writes mypy content to .claude/rules/type-safety.md."""
    (tmp_path / ".argus.yml").write_text(TYPE_SAFETY_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "mypy" in (tmp_path / ".claude/rules/type-safety.md").read_text()


ERROR_HANDLING_CONFIG = """\
packs:
  - error-handling
platforms:
  - claude
"""


def test_error_handling_pack_appears_in_packs_list():
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "error-handling" in result.output


def test_error_handling_pack_show_renders_content():
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "error-handling"])
    assert result.exit_code == 0
    assert "system boundaries" in result.output


def test_error_handling_pack_generate_injects_content(tmp_path):
    (tmp_path / ".argus.yml").write_text(ERROR_HANDLING_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "system boundaries" in (tmp_path / ".claude/rules/error-handling.md").read_text()


DOCUMENTATION_STANDARDS_CONFIG = """\
packs:
  - documentation-standards
platforms:
  - claude
"""


def test_documentation_standards_pack_appears_in_packs_list():
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "documentation-standards" in result.output


def test_documentation_standards_pack_show_renders_content():
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "documentation-standards"])
    assert result.exit_code == 0
    assert "imperative mood" in result.output


def test_documentation_standards_pack_generate_injects_content(tmp_path):
    (tmp_path / ".argus.yml").write_text(DOCUMENTATION_STANDARDS_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "imperative mood" in (tmp_path / ".claude/rules/documentation-standards.md").read_text()


SECURITY_CONFIG = """\
packs:
  - security
platforms:
  - claude
"""


def test_security_pack_appears_in_packs_list():
    """Given packs list is invoked, security appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "security" in result.output


def test_security_pack_show_renders_content():
    """Given packs show security is invoked, parameterized appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "security"])
    assert result.exit_code == 0
    assert "parameterized" in result.output


def test_security_pack_generate_injects_content(tmp_path):
    """Given a security+claude config, generate writes content to .claude/rules/security.md."""
    (tmp_path / ".argus.yml").write_text(SECURITY_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "parameterized" in (tmp_path / ".claude/rules/security.md").read_text()


PYTHON_CONFIG = """\
packs:
  - python
platforms:
  - claude
"""


def test_python_pack_appears_in_packs_list():
    """Given packs list is invoked, python appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "python" in result.output


def test_python_pack_show_renders_content():
    """Given packs show python is invoked, pathlib appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "python"])
    assert result.exit_code == 0
    assert "pathlib" in result.output


def test_python_pack_generate_injects_content(tmp_path):
    """Given a python+claude config, generate writes content to .claude/rules/python.md."""
    (tmp_path / ".argus.yml").write_text(PYTHON_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "pathlib" in (tmp_path / ".claude/rules/python.md").read_text()


TYPESCRIPT_CONFIG = """\
packs:
  - typescript
platforms:
  - claude
"""


def test_typescript_pack_appears_in_packs_list():
    """Given packs list is invoked, typescript appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "typescript" in result.output


def test_typescript_pack_show_renders_content():
    """Given packs show typescript is invoked, noImplicitAny appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "typescript"])
    assert result.exit_code == 0
    assert "noImplicitAny" in result.output


def test_typescript_pack_generate_injects_content(tmp_path):
    """Given a typescript+claude config, generate writes content to .claude/rules/typescript.md."""
    (tmp_path / ".argus.yml").write_text(TYPESCRIPT_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "noImplicitAny" in (tmp_path / ".claude/rules/typescript.md").read_text()


GO_CONFIG = """\
packs:
  - go
platforms:
  - claude
"""


def test_go_pack_appears_in_packs_list():
    """Given packs list is invoked, go appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "go" in result.output


def test_go_pack_show_renders_content():
    """Given packs show go is invoked, errors.Is appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "go"])
    assert result.exit_code == 0
    assert "errors.Is" in result.output


def test_go_pack_generate_injects_content(tmp_path):
    """Given a go+claude config, generate writes content to .claude/rules/go.md."""
    (tmp_path / ".argus.yml").write_text(GO_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "errors.Is" in (tmp_path / ".claude/rules/go.md").read_text()


JAVA_CONFIG = """\
packs:
  - java
platforms:
  - claude
"""


def test_java_pack_appears_in_packs_list():
    """Given packs list is invoked, java appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "java" in result.output


def test_java_pack_show_renders_content():
    """Given packs show java is invoked, Optional.orElseThrow appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "java"])
    assert result.exit_code == 0
    assert "Optional.orElseThrow" in result.output


def test_java_pack_generate_injects_content(tmp_path):
    """Given a java+claude config, generate writes content to .claude/rules/java.md."""
    (tmp_path / ".argus.yml").write_text(JAVA_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "Optional.orElseThrow" in (tmp_path / ".claude/rules/java.md").read_text()


KOTLIN_CONFIG = """\
packs:
  - kotlin
platforms:
  - claude
"""


def test_kotlin_pack_appears_in_packs_list():
    """Given packs list is invoked, kotlin appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "kotlin" in result.output


def test_kotlin_pack_show_renders_content():
    """Given packs show kotlin is invoked, requireNotNull appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "kotlin"])
    assert result.exit_code == 0
    assert "requireNotNull" in result.output


def test_kotlin_pack_generate_injects_content(tmp_path):
    """Given a kotlin+claude config, generate writes content to .claude/rules/kotlin.md."""
    (tmp_path / ".argus.yml").write_text(KOTLIN_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "requireNotNull" in (tmp_path / ".claude/rules/kotlin.md").read_text()


FASTAPI_CONFIG = """\
packs:
  - fastapi
platforms:
  - claude
"""


def test_fastapi_pack_appears_in_packs_list():
    """Given packs list is invoked, fastapi appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "fastapi" in result.output


def test_fastapi_pack_show_renders_content():
    """Given packs show fastapi is invoked, APIRouter appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "fastapi"])
    assert result.exit_code == 0
    assert "APIRouter" in result.output


def test_fastapi_pack_generate_injects_content(tmp_path):
    """Given a fastapi+claude config, generate writes content to .claude/rules/fastapi.md."""
    (tmp_path / ".argus.yml").write_text(FASTAPI_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "APIRouter" in (tmp_path / ".claude/rules/fastapi.md").read_text()


NEXTJS_CONFIG = """\
packs:
  - nextjs
platforms:
  - claude
"""


def test_nextjs_pack_appears_in_packs_list():
    """Given packs list is invoked, nextjs appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "list"])
    assert result.exit_code == 0
    assert "nextjs" in result.output


def test_nextjs_pack_show_renders_content():
    """Given packs show nextjs is invoked, use client appears in the output."""
    runner = CliRunner()
    result = runner.invoke(main, ["packs", "show", "nextjs"])
    assert result.exit_code == 0
    assert "use client" in result.output


def test_nextjs_pack_generate_injects_content(tmp_path):
    """Given a nextjs+claude config, generate writes content to .claude/rules/nextjs.md."""
    (tmp_path / ".argus.yml").write_text(NEXTJS_CONFIG)
    runner = CliRunner()
    result = runner.invoke(main, ["generate", "--project-root", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert "use client" in (tmp_path / ".claude/rules/nextjs.md").read_text()
