from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path

GENERATED_HEADER = (
    "<!-- Generated by argus. Run `argus generate` to update."
    " Do not edit manually. -->\n\n"
)


@dataclass
class Pack:
    name: str
    manifest: dict
    instructions: str
    checklist: str | None
    examples: str | None


@dataclass
class GeneratedFile:
    path: Path
    content: str


class BaseAdapter(ABC):
    platform_id: str
    display_name: str

    @abstractmethod
    def generate(self, packs: list[Pack]) -> list[GeneratedFile]:
        """Translate packs into one or more platform-specific files."""
        ...

    def _agents_md(self, packs: list[Pack]) -> GeneratedFile:
        sections = [GENERATED_HEADER + "# Engineering Standards\n"]
        for pack in packs:
            sections.append(f"## {pack.name.upper()}\n\n{pack.instructions}")
        return GeneratedFile(path=Path("AGENTS.md"), content="\n\n".join(sections))
