import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'installation',
    'quick-start',
    'configuration',
    'upgrade',
    'platforms',
    'ci-integration',
    {
      type: 'category',
      label: 'Packs',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'packs'},
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/adding-a-pack',
        'contributing/adding-a-platform',
      ],
    },
  ],
};

export default sidebars;
