from pathlib import Path
from argus.adapters.base import Pack, GeneratedFile, BaseAdapter, GENERATED_HEADER


def test_pack_stores_all_fields():
    pack = Pack(
        name="tdd",
        manifest={"name": "tdd", "category": "workflow"},
        instructions="# TDD instructions",
        checklist="## Checklist",
        examples="## Examples",
    )
    assert pack.name == "tdd"
    assert pack.instructions == "# TDD instructions"
    assert pack.checklist == "## Checklist"
    assert pack.examples == "## Examples"


def test_pack_allows_optional_fields_to_be_none():
    pack = Pack(
        name="solid",
        manifest={},
        instructions="# SOLID",
        checklist=None,
        examples=None,
    )
    assert pack.checklist is None
    assert pack.examples is None


def test_generated_file_stores_path_and_content():
    f = GeneratedFile(path=Path("CLAUDE.md"), content="# content")
    assert f.path == Path("CLAUDE.md")
    assert f.content == "# content"


def test_generated_header_constant_exists():
    assert "Generated by argus" in GENERATED_HEADER
    assert "argus generate" in GENERATED_HEADER


def test_base_adapter_is_abstract():
    import inspect
    assert inspect.isabstract(BaseAdapter)
